server:
  port: 8081
  servlet:
    context-path: /api


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/college
    username: postgres
    password: 9874123

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: college
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true

